DROP TABLE IF EXISTS TBL_USERS;

CREATE TABLE TBL_USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_TASKS;

CREATE TABLE TBL_TASKS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  task_description VARCHAR(250) NOT NULL,
  task_due_date VARCHAR(250) NOT NULL,
);